"""add is_active column

Revision ID: 2d59add56d49
Revises: dac33fbcd993
Create Date: 2025-10-26 13:29:51.258274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d59add56d49'
down_revision: Union[str, Sequence[str], None] = 'dac33fbcd993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('student', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('student', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student', 'grade',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'grade',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('student', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('student', 'created_at')
    op.drop_column('student', 'is_active')
    # ### end Alembic commands ###
